import type { Metadata } from "next";
import { Clock3, Mail, MapPin, Send } from "lucide-react";
import { ContactForm } from "@/components/forms/ContactForm";
import { PageHero } from "@/components/sections/PageHero";
import { Container } from "@/components/ui/Container";
import { profile } from "@/data/profile";
import { socials } from "@/data/socials";
export const metadata: Metadata = { title: "Contact", description: "Contact Alamin Akon for website design, Shopify development, UI/UX design and front-end development projects.", alternates: { canonical: "/contact" } };
export default function ContactPage() { return <><PageHero eyebrow="Contact" title="Have a project in mind?" description="Whether you need a new website, a Shopify store, a website redesign or a responsive front-end interface, let’s discuss how I can help bring your idea to life."/><section className="section-space"><Container><div className="grid items-start gap-12 lg:grid-cols-[.75fr_1.25fr]"><div><p className="text-lg leading-8 text-slate-300">Tell me what you are planning, what you would like to improve and where you are hoping to go. I&apos;ll review your message and reply as soon as I can.</p><div className="mt-9 space-y-5">{[[Mail, "Email", profile.email], [MapPin, "Location", profile.location], [Clock3, "Availability", profile.availability]].map(([Icon, label, value]) => { const ContactIcon = Icon as typeof Mail; return <div className="flex items-start gap-3" key={String(label)}><span className="grid size-10 place-items-center rounded-xl bg-primary/15 text-accent"><ContactIcon className="size-4"/></span><div><p className="text-xs font-bold uppercase tracking-[.14em] text-text-secondary">{String(label)}</p><p className="mt-1 text-sm text-slate-200">{String(value)}</p></div></div>; })}</div><div className="mt-10 border-t border-white/8 pt-7"><p className="text-xs font-bold uppercase tracking-[.18em] text-accent">Find me online</p><div className="mt-4 flex flex-wrap gap-2">{socials.map((social) => <a key={social.label} href={social.href} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 rounded-full border border-white/10 px-3 py-2 text-sm text-text-secondary transition hover:border-accent/50 hover:text-accent">{social.label}<Send className="size-3"/></a>)}</div></div></div><ContactForm/></div></Container></section></>; }
