import Link from "next/link";
import { BriefcaseBusiness, Camera, Code2, Link2, MessageCircle, Music2 } from "lucide-react";
import { Container } from "@/components/ui/Container";
import { navigation } from "@/data/navigation";
import { socials } from "@/data/socials";
import { profile } from "@/data/profile";

const socialIcons = { Fiverr: BriefcaseBusiness, GitHub: Code2, LinkedIn: Link2, Facebook: MessageCircle, Instagram: Camera, TikTok: Music2 };

export function Footer() { const year = new Date().getFullYear(); return <footer className="border-t border-white/8 bg-[#060a12] py-14"><Container><div className="grid gap-10 sm:grid-cols-2 lg:grid-cols-[1.45fr_1fr_1fr_1fr]"><div><p className="text-xl font-bold tracking-tight text-white">{profile.name}</p><p className="mt-4 max-w-xs text-sm leading-6 text-text-secondary">Web Designer and Developer creating modern, responsive and user-friendly digital experiences.</p></div><FooterLinks title="Navigation" links={navigation}/><FooterLinks title="Services" links={[{ label: "Web Design", href: "/services" }, { label: "Front-End Development", href: "/services" }, { label: "Shopify Design", href: "/services" }, { label: "UI/UX Design", href: "/services" }]}/><div><p className="mb-4 text-sm font-semibold text-white">Social</p><div className="footer-social-icons">{socials.map((item) => { const Icon = socialIcons[item.label as keyof typeof socialIcons]; return <a key={item.label} href={item.href} target="_blank" rel="noreferrer" aria-label={item.label} className={`footer-social-icon footer-social-icon-${item.label.toLowerCase()}`}><Icon className="size-[18px]" aria-hidden="true"/></a>; })}</div></div></div><div className="mt-14 flex flex-col gap-3 border-t border-white/8 pt-6 text-xs text-text-secondary sm:flex-row sm:items-center sm:justify-between"><p>© {year} Alamin Akon. All rights reserved.</p><p>{profile.tagline}</p></div></Container></footer>; }
function FooterLinks({ title, links }: { title: string; links: Array<{ label: string; href: string }> }) { return <div><p className="mb-4 text-sm font-semibold text-white">{title}</p><ul className="space-y-3">{links.map((item) => <li key={item.label}><Link href={item.href} className="text-sm text-text-secondary transition hover:text-accent">{item.label}</Link></li>)}</ul></div>; }
