import type { Metadata } from "next";
import { CheckCircle2 } from "lucide-react";
import { biography, profile } from "@/data/profile";
import { values, processSteps } from "@/data/skills";
import { Container } from "@/components/ui/Container";
import { PageHero } from "@/components/sections/PageHero";
import { SectionHeading } from "@/components/ui/SectionHeading";
import { CTASection } from "@/components/sections/CTASection";
export const metadata: Metadata = { title: "About", description: "Learn about Alamin Akon, a Web Designer and Developer creating modern, responsive and user-friendly digital experiences.", alternates: { canonical: "/about" } };
export default function AboutPage() { return <><PageHero eyebrow="About Alamin" title="Designing with intention. Developing with care." description="Web Designer and Developer creating modern, responsive and user-friendly digital experiences."/><section className="section-space"><Container><div className="grid gap-12 lg:grid-cols-[.72fr_1.28fr]"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-accent">A little more</p><h2 className="mt-4 text-3xl font-bold tracking-[-.05em] text-white sm:text-4xl">Hello, I&apos;m {profile.name}.</h2></div><div className="space-y-5 text-base leading-8 text-text-secondary"><p className="text-lg text-slate-300">{profile.introduction}</p>{biography.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div></div></Container></section><section className="section-space border-y border-white/8 bg-surface/30"><Container><SectionHeading eyebrow="Values" title="The principles behind each project."/><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{values.map(([title, description]) => <article key={title} className="rounded-3xl border border-white/8 bg-background/45 p-6"><CheckCircle2 className="size-5 text-accent"/><h3 className="mt-6 text-lg font-bold text-white">{title}</h3><p className="mt-3 text-sm leading-6 text-text-secondary">{description}</p></article>)}</div></Container></section><section className="section-space"><Container><SectionHeading eyebrow="Working approach" title="A clear path from idea to launch."/><ol className="mt-12 grid gap-3 md:grid-cols-2 lg:grid-cols-4">{processSteps.concat([{ number: "07", title: "Review & Support", description: "I review the finished work and stay ready for thoughtful future improvements." }]).map((step) => <li key={step.number} className="rounded-2xl border border-white/8 bg-white/[.02] p-5"><span className="font-mono text-xs text-accent">{step.number}</span><h3 className="mt-5 font-bold text-white">{step.title}</h3><p className="mt-2 text-sm leading-6 text-text-secondary">{step.description}</p></li>)}</ol></Container></section><CTASection title="Let’s make your next idea feel effortless." description="Whether you are starting fresh or improving an existing website, let’s talk about the right path forward."/></>; }
